spring:
  application:
    name: account-microservice

  datasource:
    url: jdbc:mysql://localhost:3310/account_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  cloud:
    config:
      allow-override: true
      override-none: false
      override-system-properties: false

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    org.springframework.cloud.openfeign: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
