spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

            
        - id: customer-service
          uri: lb://CUSTOMER-ACCOUNT
          predicates:
            - Path=/customers/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: INFO


jwt:
  secret: my-super-secret-jwt-key-which-is-at-least-32-chars





