server:
  port: 8081

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: customer-service
          uri: lb://CUSTOMER-ACCOUNT
          predicates:
            - Path=/customers/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: INFO
