spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      discovery:
        locator:
          enabled: false

      routes:

        - id: auth-service-auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: auth-service-clients
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/clients/**


logging:
  level:
    org.springframework.cloud.gateway: INFO


jwt:
  secret: my-super-secret-jwt-key-which-is-at-least-32-chars








