server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3309/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

jwt:
  secret: my-super-secret-jwt-key-which-is-at-least-32-chars
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9102/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
